Repository antvis/gatsby-theme-antv, pull requests merged in 2019-11, with the labels that each got.

#10 feat: support recursive menu and fix order
  @antv/gatsby-theme-antv/site/templates/document.tsx
  example/docs/specification/category/three/my.en.md
  example/docs/specification/category/three/my.zh.md
  example/gatsby-config.js
Labels: PR: unreviewed, enhancement

#12 feat: 增加i18n provider
  .gitignore
  @antv/gatsby-theme-antv/package.json
  @antv/gatsby-theme-antv/site/components/Header.tsx
  @antv/gatsby-theme-antv/site/components/withProvider.tsx
Labels: PR: unreviewed, enhancement

#14 feat: support insert css in example code
  @antv/gatsby-theme-antv/gatsby-browser.js
  @antv/gatsby-theme-antv/package.json
  @antv/gatsby-theme-antv/site/components/PlayGround.tsx
  example/examples/basic/demo/basic.js
  yarn.lock
Labels: PR: unreviewed, enhancement

#15 feat: Update footer data and design
  @antv/gatsby-theme-antv/package.json
  @antv/gatsby-theme-antv/site/common.json
  @antv/gatsby-theme-antv/site/components/Footer.module.less
  @antv/gatsby-theme-antv/site/components/Footer.tsx
  example/site/pages/index.zh.tsx
  yarn.lock
Labels: PR: unreviewed, enhancement

#11 Components
  @antv/gatsby-theme-antv/package.json
  @antv/gatsby-theme-antv/site/components/Banner.module.less
  @antv/gatsby-theme-antv/site/components/Banner.tsx
  @antv/gatsby-theme-antv/site/components/BannerSVG.module.less
  @antv/gatsby-theme-antv/site/components/BannerSVG.tsx
  @antv/gatsby-theme-antv/site/components/Cases.module.less
  @antv/gatsby-theme-antv/site/components/Cases.tsx
  @antv/gatsby-theme-antv/site/components/Companies.module.less
  @antv/gatsby-theme-antv/site/components/Companies.tsx
  @antv/gatsby-theme-antv/site/components/FeatureCard.module.less
  @antv/gatsby-theme-antv/site/components/FeatureCard.tsx
  @antv/gatsby-theme-antv/site/components/Features.module.less
  @antv/gatsby-theme-antv/site/components/Features.tsx
  @antv/gatsby-theme-antv/site/components/Notification.module.less
  @antv/gatsby-theme-antv/site/components/Notification.tsx
  @antv/gatsby-theme-antv/site/layouts/layout.module.less
  README.md
  example/site/locale.json
  example/site/pages/index.zh.tsx
  yarn.lock
Labels: PR: unreviewed

#17 feat: Header and Products card
  @antv/gatsby-theme-antv/gatsby-config.js
  @antv/gatsby-theme-antv/site/components/Banner.module.less
  @antv/gatsby-theme-antv/site/components/Features.module.less
  @antv/gatsby-theme-antv/site/components/Footer.tsx
  @antv/gatsby-theme-antv/site/components/Header.module.less
  @antv/gatsby-theme-antv/site/components/Header.tsx
  @antv/gatsby-theme-antv/site/components/PlayGrounds.module.less
  @antv/gatsby-theme-antv/site/components/Product.module.less
  @antv/gatsby-theme-antv/site/components/Product.tsx
  @antv/gatsby-theme-antv/site/components/Products.tsx
  @antv/gatsby-theme-antv/site/components/Search.module.less
  @antv/gatsby-theme-antv/site/components/getProducts.ts
  @antv/gatsby-theme-antv/site/pages/index.tsx
  README.md
Labels: PR: unreviewed, enhancement

#18 chore: optimize button code style
  @antv/gatsby-theme-antv/package.json
  @antv/gatsby-theme-antv/site/components/Banner.module.less
  @antv/gatsby-theme-antv/site/components/Banner.tsx
  @antv/gatsby-theme-antv/site/components/Footer.module.less
  @antv/gatsby-theme-antv/site/components/Header.module.less
  @antv/gatsby-theme-antv/site/components/Header.tsx
  @antv/gatsby-theme-antv/site/components/mixins.less
  @antv/gatsby-theme-antv/site/layouts/layout.tsx
  example/site/pages/index.zh.tsx
  yarn.lock
Labels: PR: unreviewed, chore

#19 feat: add prev and next article buttons
  @antv/gatsby-theme-antv/gatsby-node.js
  @antv/gatsby-theme-antv/site/components/Features.tsx
  @antv/gatsby-theme-antv/site/components/NavigatorBanner.module.less
  @antv/gatsby-theme-antv/site/components/NavigatorBanner.tsx
  @antv/gatsby-theme-antv/site/templates/document.tsx
  @antv/gatsby-theme-antv/site/templates/example.tsx
  @antv/gatsby-theme-antv/site/templates/markdown.module.less
  example/examples/category/second/index.zh.md
Labels: PR: unreviewed, enhancement

#23 feat: Add menu icon on mobile device
  @antv/gatsby-theme-antv/package.json
  @antv/gatsby-theme-antv/site/components/Header.module.less
  @antv/gatsby-theme-antv/site/components/Header.tsx
  @antv/gatsby-theme-antv/site/components/Products.tsx
  yarn.lock
Labels: PR: unreviewed, enhancement

#24 feat: Add doc menu in drawer
  @antv/gatsby-theme-antv/gatsby-browser.js
  @antv/gatsby-theme-antv/package.json
  @antv/gatsby-theme-antv/site/templates/document.tsx
  @antv/gatsby-theme-antv/site/templates/example.tsx
  @antv/gatsby-theme-antv/site/templates/markdown.module.less
  yarn.lock
Labels: PR: reviewed-changes-requested, enhancement

#25 Style adjustment
  @antv/gatsby-theme-antv/site/components/Banner.module.less
Labels: PR: unreviewed

#26 Style adjustment
  @antv/gatsby-theme-antv/site/components/Banner.module.less
  @antv/gatsby-theme-antv/site/components/Banner.tsx
  example/site/pages/index.zh.tsx
Labels: PR: unreviewed

#30 feat: 🇨🇳 open notification for china mirror
  @antv/gatsby-theme-antv/site/components/Footer.tsx
Labels: PR: unreviewed, enhancement

#32 fix: static classnames for rewriting styles outside
  @antv/gatsby-theme-antv/site/components/Banner.tsx
Labels: PR: unreviewed, add, bug

#34 fix: mobile menu
  @antv/gatsby-theme-antv/package.json
  @antv/gatsby-theme-antv/site/components/Header.module.less
  @antv/gatsby-theme-antv/site/components/Header.tsx
  @antv/gatsby-theme-antv/site/templates/document.tsx
  @antv/gatsby-theme-antv/site/templates/example.tsx
  @antv/gatsby-theme-antv/site/templates/markdown.module.less
  yarn.lock
Labels: PR: unreviewed, bug

#38 feat: play and close video callback functions
  @antv/gatsby-theme-antv/site/components/Banner.tsx
  example/site/pages/index.zh.tsx
Labels: PR: unreviewed, enhancement

#42 feat: 🗑 remove gatsby-offline-plugin for strange render
  @antv/gatsby-theme-antv/README.md
  @antv/gatsby-theme-antv/gatsby-config.js
  @antv/gatsby-theme-antv/package.json
  README.md
  yarn.lock
Labels: PR: unreviewed, enhancement

#43 fix: download button link to another page. fix: notification covered …
  @antv/gatsby-theme-antv/site/components/Banner.module.less
  @antv/gatsby-theme-antv/site/components/Banner.tsx
  example/site/pages/index.zh.tsx
Labels: PR: unreviewed, bug

#46 feat: 🇨🇳 china mirror link
  @antv/gatsby-theme-antv/site/components/Header.module.less
  @antv/gatsby-theme-antv/site/components/Header.tsx
  @antv/gatsby-theme-antv/site/components/Search.module.less
  @antv/gatsby-theme-antv/site/images/external-link.svg
  @antv/gatsby-theme-antv/site/layouts/layout.tsx
Labels: PR: unreviewed, enhancement

#49 fix: video button hover scroll. fix: videa modal style
  @antv/gatsby-theme-antv/site/components/Banner.module.less
Labels: PR: unreviewed, bug

#51 fix:video link error. fix:g2plot description
  @antv/gatsby-theme-antv/site/common.json
  @antv/gatsby-theme-antv/site/components/Banner.tsx
  @antv/gatsby-theme-antv/site/components/getProducts.tsx
  example/site/pages/index.zh.tsx
Labels: PR: unreviewed

#58 fix: banner button alignment
  @antv/gatsby-theme-antv/site/components/Banner.module.less
Labels: PR: unreviewed, bug

#60 fix: banner image alignment on mobile
  @antv/gatsby-theme-antv/site/components/Banner.module.less
Labels: PR: unreviewed, bug

#67 feat: Add docsearchOptions to theme options
  @antv/gatsby-theme-antv/gatsby-node.js
  @antv/gatsby-theme-antv/site/components/Header.tsx
  @antv/gatsby-theme-antv/site/components/Search.tsx
  @antv/gatsby-theme-antv/site/layouts/layout.tsx
Labels: PR: reviewed-changes-requested, enhancement
