Repository antvis/gatsby-theme-antv, pull requests merged in 2020-11, with the labels that each got.

#237 chore: fix gatsby preview
  .github/workflows/nodejs.yml
  .github/workflows/preview.yml
  example/package.json
Labels: PR: unreviewed

#238 fix: fix code merge error
  @antv/gatsby-theme-antv/gatsby-node.js
  @antv/gatsby-theme-antv/site/templates/markdown.module.less
Labels: PR: reviewed-approved

#239 fix: change version dependencies for new release
  example/package.json
Labels: PR: unreviewed

#241 fix: thumbnail fit in container
  @antv/gatsby-theme-antv/site/templates/markdown.module.less
Labels: PR: unreviewed

#240 feat: Read news from My JSON Server
  @antv/gatsby-theme-antv/package.json
  @antv/gatsby-theme-antv/site/components/APIDoc.tsx
  @antv/gatsby-theme-antv/site/components/Banner.tsx
  @antv/gatsby-theme-antv/site/components/CodeLoading.tsx
  @antv/gatsby-theme-antv/site/components/Footer.tsx
Labels: PR: unreviewed

#243 style: markdown 中的 ul ol 样式不对
  @antv/gatsby-theme-antv/site/templates/markdown.module.less
Labels: PR: partially-approved

#247 fix: optimize markdown styles
  @antv/gatsby-theme-antv/site/templates/markdown.module.less
Labels: PR: unreviewed

#246 fix: optimize style of nav
  @antv/gatsby-theme-antv/site/templates/document.tsx
  @antv/gatsby-theme-antv/site/templates/example.tsx
  @antv/gatsby-theme-antv/site/templates/markdown.module.less
Labels: PR: reviewed-approved

#251 fix: surge-preview
  .github/workflows/preview.yml
  @antv/gatsby-theme-antv/site/layouts/layout.tsx
Labels: PR: unreviewed

#249 style: revert markdown text color
  @antv/gatsby-theme-antv/site/templates/markdown.module.less
Labels: PR: unreviewed

#253 style(💄): tweak layout switcher style
  @antv/gatsby-theme-antv/site/components/LayoutIcons.tsx
  @antv/gatsby-theme-antv/site/components/LayoutSwitcher.module.less
  @antv/gatsby-theme-antv/site/components/LayoutSwitcher.tsx
Labels: PR: unreviewed

#254 fix: resolved multiple document issues with the API directory
  @antv/gatsby-theme-antv/site/templates/document.tsx
Labels: PR: reviewed-approved

#255 fix: fixed an unrevocable editor issue
  @antv/gatsby-theme-antv/site/components/PlayGround.tsx
Labels: PR: unreviewed

#256 style: tewak the style of header for AntV new homepage
  @antv/gatsby-theme-antv/gatsby-node.js
  @antv/gatsby-theme-antv/site/components/Header.module.less
  @antv/gatsby-theme-antv/site/components/Header.tsx
  @antv/gatsby-theme-antv/site/images/antvhome.svg
  @antv/gatsby-theme-antv/site/layouts/layout.tsx
  README.md
  example/gatsby-config.js
Labels: PR: reviewed-approved

#257 fix: fixed an unrevocable edit problem
  @antv/gatsby-theme-antv/site/components/MdPlayground.tsx
Labels: PR: unreviewed

#258 fix: fix regexp error in safari
  @antv/gatsby-theme-antv/gatsby-node.js
  @antv/gatsby-theme-antv/package.json
  yarn.lock
Labels: PR: unreviewed

#242 feat: Theme switcher
  @antv/gatsby-theme-antv/README.md
  @antv/gatsby-theme-antv/gatsby-config.js
  @antv/gatsby-theme-antv/gatsby-node.js
  @antv/gatsby-theme-antv/package.json
  @antv/gatsby-theme-antv/site/common.json
  @antv/gatsby-theme-antv/site/components/APIDoc.module.less
  @antv/gatsby-theme-antv/site/components/APIDoc.tsx
  @antv/gatsby-theme-antv/site/components/LayoutSwitcher.module.less
  @antv/gatsby-theme-antv/site/components/LayoutSwitcher.tsx
  @antv/gatsby-theme-antv/site/components/PlayGround.module.less
  @antv/gatsby-theme-antv/site/components/PlayGround.tsx
  @antv/gatsby-theme-antv/site/components/Swatch.module.less
  @antv/gatsby-theme-antv/site/components/Swatch.tsx
  @antv/gatsby-theme-antv/site/components/Tabs.module.less
  @antv/gatsby-theme-antv/site/components/Tabs.tsx
  @antv/gatsby-theme-antv/site/components/ThemeSwitcher.module.less
  @antv/gatsby-theme-antv/site/components/ThemeSwitcher.tsx
  @antv/gatsby-theme-antv/site/components/Toolbar.module.less
  @antv/gatsby-theme-antv/site/global.less
  @antv/gatsby-theme-antv/site/images/color-switcher.svg
  @antv/gatsby-theme-antv/site/images/empty.svg
  @antv/gatsby-theme-antv/site/images/watermark.svg
  @antv/gatsby-theme-antv/site/layouts/layout.tsx
  @antv/gatsby-theme-antv/site/pallette.json
  @antv/gatsby-theme-antv/site/templates/markdown.module.less
  README.md
  example/docs/specification/test-only-cn.md
  example/examples/category/basic/API.zh.md
  example/examples/category/second/API.en.md
  example/examples/category/second/API.zh.md
  example/examples/category/second/design.zh.md
  example/examples/radar/basic/API.en.md
  example/examples/radar/basic/API.zh.md
  example/examples/radar/basic/demo/basic.ts
  example/examples/radar/basic/demo/crosshairs.ts
  example/examples/radar/basic/demo/meta.json
  example/examples/radar/basic/demo/series.ts
  example/examples/radar/basic/index.en.md
  example/examples/radar/basic/index.zh.md
  example/examples/scatter/basic/API.en.md
  example/examples/scatter/basic/API.zh.md
  example/examples/scatter/basic/demo/basic.ts
  example/examples/scatter/basic/demo/color-mapping.ts
  example/examples/scatter/basic/demo/label.ts
  example/examples/scatter/basic/demo/meta.json
  example/examples/scatter/basic/demo/quadrant.ts
  example/examples/scatter/basic/demo/shape-mapping.ts
  example/examples/scatter/basic/demo/size.ts
  example/examples/scatter/basic/design.en.md
  example/examples/scatter/basic/design.zh.md
  example/examples/scatter/basic/index.en.md
  example/examples/scatter/basic/index.zh.md
  example/gatsby-browser.js
  example/gatsby-config.js
  example/package.json
  yarn.lock
Labels: PR: partially-approved

#259 feat: tweak layout of example for antv home site
  @antv/gatsby-theme-antv/site/components/APIDoc.module.less
  @antv/gatsby-theme-antv/site/components/APIDoc.tsx
  @antv/gatsby-theme-antv/site/components/PlayGround.tsx
  @antv/gatsby-theme-antv/site/components/Tabs.tsx
  @antv/gatsby-theme-antv/site/templates/example.tsx
  README.md
  yarn.lock
Labels: PR: partially-approved

#261 fix: solve the problem of incomplete tutorial directory
  @antv/gatsby-theme-antv/site/templates/document.tsx
Labels: PR: unreviewed

#263 test hang loading
  @antv/gatsby-theme-antv/site/layouts/layout.module.less
Labels: PR: unreviewed

#264 feat: switch to two columns layout when there is no API and no design in example.
  @antv/gatsby-theme-antv/site/components/APIDoc.module.less
  @antv/gatsby-theme-antv/site/components/APIDoc.tsx
  @antv/gatsby-theme-antv/site/components/PlayGround.module.less
  @antv/gatsby-theme-antv/site/components/PlayGround.tsx
  @antv/gatsby-theme-antv/site/components/Tabs.tsx
  @antv/gatsby-theme-antv/site/layoutConfig.ts
  @antv/gatsby-theme-antv/site/templates/example.tsx
  README.md
  example/examples/basic/API.en.md
  example/examples/basic/API.zh.md
  example/examples/basic/design.en.md
  example/examples/basic/index.en.md
Labels: PR: reviewed-approved

#265 New produt info
  @antv/gatsby-theme-antv/package.json
  @antv/gatsby-theme-antv/site/common.json
  @antv/gatsby-theme-antv/site/components/Footer.module.less
  @antv/gatsby-theme-antv/site/components/Footer.tsx
  @antv/gatsby-theme-antv/site/components/Header.module.less
  @antv/gatsby-theme-antv/site/components/Header.tsx
  @antv/gatsby-theme-antv/site/components/RedirectIndex.tsx
  @antv/gatsby-theme-antv/site/components/getProducts.tsx
  @antv/gatsby-theme-antv/site/components/test.json
  @antv/gatsby-theme-antv/site/images/antvhome.svg
  @antv/gatsby-theme-antv/site/layouts/layout.module.less
  @antv/gatsby-theme-antv/site/layouts/layout.tsx
  example/site/locale.json
  example/site/pages/index.zh.tsx
Labels: PR: unreviewed

#266 fix: fix theme switcher for g2 & g2plot
  @antv/gatsby-theme-antv/package.json
  @antv/gatsby-theme-antv/site/components/PlayGround.module.less
  @antv/gatsby-theme-antv/site/components/PlayGround.tsx
  @antv/gatsby-theme-antv/site/templates/example.tsx
  example/examples/basic/demo/ts-demo.ts
  example/package.json
  yarn.lock
Labels: PR: unreviewed

#269 style: fix Header products card style
  @antv/gatsby-theme-antv/site/components/Article.module.less
  @antv/gatsby-theme-antv/site/components/Product.module.less
Labels: PR: unreviewed

#270 fix: header and footer style
  @antv/gatsby-theme-antv/site/components/Footer.module.less
  @antv/gatsby-theme-antv/site/components/Footer.tsx
  @antv/gatsby-theme-antv/site/components/Header.module.less
  @antv/gatsby-theme-antv/site/components/Product.module.less
  example/gatsby-browser.js
Labels: PR: unreviewed

#271 fix: demo 页面优化
  @antv/gatsby-theme-antv/site/common.json
  @antv/gatsby-theme-antv/site/components/APIDoc.module.less
  @antv/gatsby-theme-antv/site/components/PlayGround.module.less
  @antv/gatsby-theme-antv/site/components/Tabs.module.less
  @antv/gatsby-theme-antv/site/components/ThemeSwitcher.module.less
  @antv/gatsby-theme-antv/site/components/getProducts.tsx
  @antv/gatsby-theme-antv/site/templates/example.tsx
  example/docs/specification/test-only-cn.md
Labels: PR: unreviewed

#272 fix: product_info
  @antv/gatsby-theme-antv/site/components/getProducts.tsx
Labels: PR: unreviewed

#275 fix: footer ava urls
  @antv/gatsby-theme-antv/site/components/getProducts.tsx
Labels: PR: unreviewed

#276 refactor: gatsby-plugin-google-analytics => gatsby-plugin-google-gtag
  @antv/gatsby-theme-antv/gatsby-config.js
  @antv/gatsby-theme-antv/package.json
  @antv/gatsby-theme-antv/site/pages/404.tsx
  yarn.lock
Labels: PR: unreviewed
