Repository antvis/gatsby-theme-antv, pull requests merged in 2020-03, with the labels that each got.

#110 chore: Upgrade antd
  @antv/gatsby-theme-antv/jest.setup.js
  @antv/gatsby-theme-antv/package.json
  @antv/gatsby-theme-antv/site/components/Banner.tsx
  @antv/gatsby-theme-antv/site/components/Cases.tsx
  @antv/gatsby-theme-antv/site/components/Footer.tsx
  @antv/gatsby-theme-antv/site/components/Header.module.less
  @antv/gatsby-theme-antv/site/components/Header.tsx
  @antv/gatsby-theme-antv/site/components/PageLoading.tsx
  @antv/gatsby-theme-antv/site/components/Search.tsx
  @antv/gatsby-theme-antv/site/components/Toolbar.tsx
  @antv/gatsby-theme-antv/site/components/getProducts.tsx
  @antv/gatsby-theme-antv/site/pages/404.tsx
  @antv/gatsby-theme-antv/site/templates/document.tsx
  @antv/gatsby-theme-antv/site/templates/example.tsx
  @antv/gatsby-theme-antv/site/templates/markdown.module.less
  README.md
  yarn.lock
Labels: chore

#113 make primary color consistent
  @antv/gatsby-theme-antv/site/components/Companies.module.less
  @antv/gatsby-theme-antv/site/components/Features.module.less
Labels: PR: unreviewed

#117 chore: 🆙 upgrade react-codemirror2 and @testing-library/react
  @antv/gatsby-theme-antv/package.json
Labels: PR: unreviewed, chore
