Repository antvis/gatsby-theme-antv, pull requests merged in 2021-03, with the labels that each got.

#307 fix: add ChinaMirror url for antv home site
  @antv/gatsby-theme-antv/site/components/Header.tsx
Labels: PR: reviewed-approved

#309 chore: remove yunfengdie from site footer
  @antv/gatsby-theme-antv/site/components/Footer.tsx
Labels: PR: unreviewed

#312 fix: missing English translations
  @antv/gatsby-theme-antv/site/common.json
Labels: PR: unreviewed

#313 fix: 修复 md playground 设置宽度不生效 & 版本锁定解决playground无法运作
  @antv/gatsby-theme-antv/site/components/APIDoc.tsx
  @antv/gatsby-theme-antv/site/components/MdPlayground.tsx
  example/api-extractor.json
  example/docs/api/g2plot/scatter.en.md
  example/docs/api/g2plot/scatter.zh.md
  example/gatsby-config.js
  package.json
Labels: PR: partially-approved

#314 feat(docs-contributors): 文档添加贡献者信息
  @antv/gatsby-theme-antv/gatsby-node.js
  @antv/gatsby-theme-antv/site/common.json
  @antv/gatsby-theme-antv/site/components/Contributors.module.less
  @antv/gatsby-theme-antv/site/components/Contributors.tsx
  @antv/gatsby-theme-antv/site/templates/document.tsx
  @antv/gatsby-theme-antv/site/templates/markdown.module.less
  example/docs/api/g2plot/scatter.en.md
  example/docs/api/g2plot/scatter.zh.md
Labels: PR: unreviewed

#315 fix: 移除文档贡献者 label, 否则没有贡献者也会展示，有点丑
  @antv/gatsby-theme-antv/site/components/Contributors.tsx
  @antv/gatsby-theme-antv/site/templates/document.tsx
  @antv/gatsby-theme-antv/site/templates/markdown.module.less
Labels: PR: unreviewed
