Repository antvis/gatsby-theme-antv, pull requests merged in 2021-06, with the labels that each got.

#330 chore: adjust theme url
  @antv/gatsby-theme-antv/site/components/ThemeSwitcher.tsx
Labels: PR: unreviewed

#332 fix: transform searched x6 sites url
  @antv/gatsby-theme-antv/site/components/Search.tsx
Labels: PR: unreviewed

#334 feat: 在 header 中显示 github star
  @antv/gatsby-theme-antv/gatsby-node.js
  @antv/gatsby-theme-antv/jest.config.js
  @antv/gatsby-theme-antv/package.json
  @antv/gatsby-theme-antv/site/components/Announcement.tsx
  @antv/gatsby-theme-antv/site/components/Contributors.tsx
  @antv/gatsby-theme-antv/site/components/Header.module.less
  @antv/gatsby-theme-antv/site/components/Header.tsx
  @antv/gatsby-theme-antv/site/components/MdPlayground.tsx
  @antv/gatsby-theme-antv/site/components/PlayGround.tsx
  @antv/gatsby-theme-antv/site/components/TopBanner.tsx
  @antv/gatsby-theme-antv/site/layouts/layout.tsx
  @antv/gatsby-theme-antv/site/templates/example.tsx
  README.md
  example/gatsby-browser.js
  yarn.lock
Labels: PR: partially-approved

#335 feat: 图表示例添加 三级菜单栏 + 搜索框
  @antv/gatsby-theme-antv/gatsby-node.js
  @antv/gatsby-theme-antv/site/components/PlayGround.tsx
  @antv/gatsby-theme-antv/site/components/PlayGrounds.module.less
  @antv/gatsby-theme-antv/site/components/PlayGrounds.tsx
  @antv/gatsby-theme-antv/site/templates/example.tsx
Labels: PR: unreviewed

#336 Upgrade example select
  @antv/gatsby-theme-antv/gatsby-node.js
  @antv/gatsby-theme-antv/site/components/PlayGround.tsx
  @antv/gatsby-theme-antv/site/components/PlayGrounds.module.less
  @antv/gatsby-theme-antv/site/components/PlayGrounds.tsx
  @antv/gatsby-theme-antv/site/templates/example.tsx
  example/gatsby-config.js
  yarn.lock
Labels: PR: reviewed-approved

#337 fix: 修复获取examples侧边导航栏数据错误
  @antv/gatsby-theme-antv/site/components/PlayGround.tsx
Labels: PR: unreviewed

#338 feat: 提升 createPages 的性能
  @antv/gatsby-theme-antv/gatsby-node.js
Labels: PR: unreviewed
